[tool.poetry]
name = "velogames"
version = "0.1.0"
description = ""
authors = ["jeremad <jeremy.tellaa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.28.2"
beautifulsoup4 = "4.12.2"
numpy = "1.24.2"
pandas = "2.0.0"
Pyomo = "6.5.0"
python-twitter = "3.5"
tomlkit = "0.11.7"

[tool.poetry.dev-dependencies]
black = "23.3.0"
flake8 = "6.0.0"
mypy = "1.2.0"
types-requests = "^2.28.0.0"
pytest = "7.3.1"
pytest-cov = "4.0.0"
isort = "5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scrap = 'velogames.main:scrap'
compute = 'velogames.main:main'
