[tool.poetry]
name = "velogames"
version = "0.1.0"
description = ""
authors = ["jeremad <jeremy.tellaa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "2.27.1"
beautifulsoup4 = "4.11.1"
numpy = "1.22.3"
pandas = "1.4.2"
Pyomo = "6.4.0"
python-twitter = "3.5"
tomlkit = "0.10.2"

[tool.poetry.dev-dependencies]
black = "22.3.0"
flake8 = "4.0.1"
mypy = "0.950"
types-requests = "^2.25.0"
pytest = "6.2.4"
pytest-cov = "2.12.1"
isort = "5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scrap = 'velogames.scrapper:scrap'
compute = 'velogames.main:main'
