[tool.poetry]
name = "velogames"
version = "0.1.0"
description = ""
authors = ["jeremad <jeremy.tellaa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "2.28.1"
beautifulsoup4 = "4.11.1"
numpy = "1.23.3"
pandas = "1.5.0"
Pyomo = "6.4.2"
python-twitter = "3.5"
tomlkit = "0.11.5"

[tool.poetry.dev-dependencies]
black = "22.10.0"
flake8 = "5.0.4"
mypy = "0.982"
types-requests = "^2.28.0.0"
pytest = "7.1.3"
pytest-cov = "4.0.0"
isort = "5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scrap = 'velogames.main:scrap'
compute = 'velogames.main:main'
