[tool.poetry]
name = "velogames"
version = "0.1.0"
description = ""
authors = ["jeremad <jeremy.tellaa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "2.27.1"
beautifulsoup4 = "4.11.1"
numpy = "1.22.4"
pandas = "1.4.2"
Pyomo = "6.4.1"
python-twitter = "3.5"
tomlkit = "0.11.0"

[tool.poetry.dev-dependencies]
black = "22.3.0"
flake8 = "4.0.1"
mypy = "0.961"
types-requests = "^2.27.0"
pytest = "7.1.2"
pytest-cov = "3.0.0"
isort = "5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scrap = 'velogames.main:scrap'
compute = 'velogames.main:main'
