[tool.poetry]
name = "velogames"
version = "0.1.0"
description = ""
authors = ["jeremad <jeremy.tellaa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.31.0"
beautifulsoup4 = "4.12.2"
numpy = "1.25.2"
pandas = "2.0.3"
Pyomo = "6.5.0"
python-twitter = "3.5"
tomlkit = "0.12.1"
google-api-python-client = "^2.90.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^1.0.0"
oauth2client = "^4.1.3"
types-httplib2 = "^0.22.0.1"

[tool.poetry.dev-dependencies]
black = "23.7.0"
flake8 = "6.1.0"
mypy = "1.4.1"
types-requests = "^2.31.0.0"
pytest = "7.4.0"
pytest-cov = "4.1.0"
isort = "5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scrap = 'velogames.main:scrap'
compute = 'velogames.main:main'
form = 'velogames.main:create_form'
