[tool.poetry]
name = "velogames"
version = "0.1.0"
description = ""
authors = ["jeremad <jeremy.tellaa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
beautifulsoup4 = "^4.9.3"
numpy = "^1.20.3"
pandas = "^1.2.4"
Pyomo = "^6.0.1"

[tool.poetry.dev-dependencies]
black = "21.6b0"
flake8 = "3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scrap = 'velogames.scrapper:scrap'
compute = 'velogames.main:main'
