on: [workflow_dispatch]

jobs:
  compute:
    runs-on: ubuntu-latest
    steps:
      - name: install glpk
        run: sudo apt install glpk-utils
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install and configure poetry
        run: python -m pip install poetry
      - uses: actions/checkout@v4
      - name: Install python packages
        run: python -m poetry install --without dev
      - name: Compute the best possible team
        run: python -m poetry run compute
        env:
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          BSKY_HANDLE: ${{ vars.BSKY_HANDLE }}
