on: [workflow_dispatch]

jobs:
  compute:
    runs-on: ubuntu-latest
    steps:
      - name: install glpk
        run: sudo apt install glpk-utils
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install and configure poetry
        run: python -m pip install poetry
      - uses: actions/checkout@v4
      - name: Install python packages
        run: python -m poetry install --no-dev
      - name: Compute the best possible team
        run: python -m poetry run compute
        env:
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
